CREATE DATABASE data;
USE data;

CREATE TABLE UserTable (
 UserID AUTO_INCREMENT NUMBER,
  UserName VARCHAR2(40 CHAR),
  PRIMARY KEY (ID),
);
CREATE TABLE ProductTable(
  ID AUTO_INCREMENT NUMBER,
  Name VARCHAR2(32 CHAR),
  Type VARCHAR2(8 CHAR),
 UserID NUMBER,
 PRIMARY KEY (ID),
    FOREIGN KEY (userID) REFERENCES UserTable(UserID)
);

CREATE TABLE BasketTable(
ID AUTO_INCREMENT NUMBER,
  ProductID NUMBER,
 UserID NUMBER,
 PRIMARY KEY (ID),
    FOREIGN KEY (ProductID) REFERENCES ProductTable(ID),
    FOREIGN KEY (userID) REFERENCES UserTable(UserID)
);